class GSWIcons {
  GSWIcons._();

  static const String verified = 'assets/icons/verified.svg';
  static const String arrowRight = 'assets/icons/arrow_right.svg';
  static const String helpChoose = 'assets/icons/help_choose.svg';
  static const String location = 'assets/icons/location.svg';
  static const String dumbell = 'assets/icons/dumbell.svg';
  static const String yoga = 'assets/icons/yoga.svg';
  static const String nutrition = 'assets/icons/nutrition.svg';
  static const String recovery = 'assets/icons/recovery.svg';
  static const String arrowheadDown = 'assets/icons/arrowhead_down.svg';
  static const String arrowheadLeft = 'assets/icons/arrowhead_left.svg';
  static const String arrowheadUp = 'assets/icons/arrowhead_up.svg';
  static const String arrowheadRight = 'assets/icons/arrowhead_right.svg';
  static const String mobility = 'assets/icons/mobility.svg';
  static const String prePostNatal = 'assets/icons/pre_post_natal.svg';
  static const String coreStrength = 'assets/icons/core_strength.svg';
  static const String filter = 'assets/icons/filter.svg';
  static const String invisible = 'assets/icons/invisible.svg';
  static const String clock = 'assets/icons/time.svg';
  static const String calender = 'assets/icons/calender.svg';
  static const String calendar = 'assets/icons/calendar.svg';
  static const String cash = 'assets/icons/cash.svg';
  static const String close = 'assets/icons/close.svg';
  static const String edit = 'assets/icons/edit.svg';
  static const String check = 'assets/icons/check.svg';
  static const String chatCheck = 'assets/icons/chat_check.svg';
  static const String whatsapp = 'assets/icons/whatsapp.svg';
  static const String bell = 'assets/icons/bell.svg';
  static const String home = 'assets/icons/home.svg';
  static const String search = 'assets/icons/search.svg';
  static const String conditioning = 'assets/icons/conditioning.svg';
  static const String profile = 'assets/icons/profile.svg';
  static const String fatLoss = 'assets/icons/fat-loss.svg';
  static const String muscleBuilding = 'assets/icons/muscle-building.svg';
  static const String generalFitness = 'assets/icons/general-fitness.svg';
  static const String functionalTraining = 'assets/icons/functional-training.svg';
  static const String goal = 'assets/icons/Goal.svg';
}
